[run]
init_cmds = [
	["go", "install"],
	["go", "build"],
	["./raintank-metric"]
]						# Commands run in start
watch_all = true		# Watch all sub-directories
watch_dirs = ["metricstore", "metricdef", "eventdef", "qproc", "setting"]			# Directories to watch
watch_exts = [".go"]	# Extensions to watch
build_delay = 1500		# Minimal interval to Trigger build event
cmds = [
	["go", "install"],
	["go", "build"],
	["./raintank-metric"]
]						# Commands to run

[sync]
listen_addr = ":5050"
remote_addr = ":5050"